name: RSpec CI
on:
  push:
    branches:
      - 'main'
      - '*-maintenance'
      - '*-dev'
      - 'pr-*'
  pull_request:
    branches:
      - '*'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    name: 'Ruby: ${{ matrix.ruby }}, Rails: ${{ matrix.env.RAILS_VERSION }}'
    runs-on: 'ubuntu-latest'
    strategy:
      fail-fast: false
      matrix:
       include:
         - ruby: '3.2'
         - ruby: '3.1'
         - ruby: '3.0'
         - ruby: 2.7
         - ruby: 2.6
         - ruby: 2.5
         - ruby: 2.3
         - ruby: 2.2
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - run: script/update_rubygems_and_install_bundler
      - run: bundle install --binstubs
      - run: script/run_build

  legacy:
    name: Legacy Ruby Builds (${{ matrix.container.version }})
    runs-on: 'ubuntu-latest'
    container:
      image: ${{ matrix.container.tag }}
      options: ${{ matrix.container.options || '--add-host github-complains-if-this-is-empty.com:127.0.0.1' }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - container:
              version: "2.1.9"
              tag: ghcr.io/rspec/docker-ci:2.1.9
              post: git config --global --add safe.directory `pwd`
          - container:
              version: "2.0"
              tag: ghcr.io/rspec/docker-ci:2.0.0
          - container:
              version: "1.9.3"
              tag: ghcr.io/rspec/docker-ci:1.9.3
    env:
      LEGACY_CI: true
    steps:
      - run: git config --global --add safe.directory $GITHUB_WORKSPACE
      - run: git init $GITHUB_WORKSPACE
      - run: git remote add origin https://github.com/rspec/rspec-collection_matchers
      - run: git config --local gc.auto 0
      - run: git fetch --no-tags --prune --no-recurse-submodules --depth=1 origin +$GITHUB_SHA:$GITHUB_REF
      - run: git checkout --progress --force $GITHUB_REF
      - run: script/legacy_setup.sh
      - run: script/run_build
